name: Develop_test
on: workflow_dispatch
jobs:
  test_coverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flutter-version: [ 3.6.0 ]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set Up Java
        uses: actions/setup-java@v3.12.0
        with:
          distribution: 'oracle'
          java-version: '17'
      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '${{ matrix.node-version }}'
          channel: 'stable'
      - name: Install Dependencies
        run: flutter pub get
      - name: Test coverage
        run: flutter test --coverage
      - name: Check coverage
        run: flutter pub global activate dlcov && flutter pub global run dlcov -c 80
      